version: "3"

networks:
  spa:

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx-spa
    restart: always
    ports:
      - 1001:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
      - redis
      - mysql
      - adminer
    networks:
      - spa

  mysql:
    image: mysql:8.0.23
    container_name: mysql-spa
    tty: true
    restart: always
    ports:
      - 1002:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: spa
      MYSQL_USER: root
      MYSQL_PASSWORD: buyung
      MYSQL_ROOT_PASSWORD: buyung
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - spa

  adminer:
    build:
      context: .
      dockerfile: adminer.dockerfile
    container_name: adminer-spa
    restart: always
    ports:
      - 1003:8080
    networks:
      - spa

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php-spa
    restart: always
    volumes:
      - ./src:/var/www/html
    networks:
      - spa

  redis:
    image: redis:alpine
    container_name: redis-spa
    restart: always
    ports:
      - 1004:6379
    networks:
      - spa

  composer:
    # build:
    #   context: .
    #   dockerfile: composer.dockerfile
    image: composer:latest
    container_name: composer-spa
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    # depends_on:
    #   - php
    # user: laravel
    # entrypoint: ["composer"]
    networks:
      - spa

  npm:
    image: node:13.7
    container_name: npm-spa
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]
    networks:
      - spa

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: artisan-spa
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    user: laravel
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - spa
