version: "3"

networks:
  ayoserverv2:

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx-ayoserverv2
    restart: always
    ports:
      - 1001:80
    volumes:
      - ./app:/var/www/html
    depends_on:
      - php
      - redis
      - mysql
      - adminer
      - websocket
    networks:
      - ayoserverv2

  mysql:
    image: mysql:8.0.23
    container_name: mysql-ayoserverv2
    tty: true
    restart: always
    ports:
      - 1002:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ayoserverv2
      MYSQL_USER: root
      MYSQL_PASSWORD: buyung
      MYSQL_ROOT_PASSWORD: buyung
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - ayoserverv2

  adminer:
    build:
      context: .
      dockerfile: adminer.dockerfile
    container_name: adminer-ayoserverv2
    restart: always
    ports:
      - 1003:8080
    networks:
      - ayoserverv2

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php-ayoserverv2
    restart: always
    volumes:
      - ./app:/var/www/html
    networks:
      - ayoserverv2

  redis:
    image: redis:alpine
    container_name: redis-ayoserverv2
    restart: always
    ports:
      - 1004:6379
    networks:
      - ayoserverv2

  composer:
    image: composer:latest
    container_name: composer-ayoserverv2
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    networks:
      - ayoserverv2

  npm:
    image: node:14.16.0
    container_name: npm-ayoserverv2
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]
    networks:
      - ayoserverv2

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: artisan-ayoserverv2
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    user: laravel
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - ayoserverv2

  websocket:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: websocket-ayoserverv2
    working_dir: /var/www/html
    user: laravel
    restart: always
    volumes:
      - ./app:/var/www/html
    command: ["sh", "-c", "php /var/www/html/artisan websockets:serve --host=0.0.0.0"]
    ports:
      - 6001:6001
    depends_on:
      - php
    networks:
      - ayoserverv2